### ISSUE TITLE
Implement collision detection

### ISSUE THREAD

**Issue by rpahle** [vipra-uwf/vipra-1.0#101]
Boost and R-tree

**Comment by rpahle** [comment]
Most people leave the plane
- some race condition is preventing the rest leaving
- investigation on figuring out why they are not leaving
- investigation into why they are bunching too close together

**Comment by satkkeerthi** [comment]
#94 continues here.

**Comment by satkkeerthi** [comment]
Further testing and fixing of corner case issues, where some passengers are stuck in an infinite loop of race conditions. Added a race counter, which limits the amount of time that a passenger is in a race condition.

**Comment by satkkeerthi** [comment]
Still facing issues where passengers are still clumping too close together, even after increasing the intersection boundary size for the passengers. Current output is as follows.

![currentoutput](https://user-images.githubusercontent.com/113207522/218866065-bb628387-c61c-4b18-ab91-5089eda6923d.gif)

**Comment by satkkeerthi** [comment]
Passengers phase through each other.
Possible fixes to attempt:
Make passengers only winners for one timestep.
Run race condition at the beginning of the timestep and ignore the race opp as nearest neighbour.
Check goal comparisons.

**Comment by satkkeerthi** [comment]
Race conditions have been implemented. Each passenger checks if it has the highest priority in its collision boundary. If it doesn't, it waits until it does. Preview of how the deplaning works is as follows:
![outputnolabel](https://user-images.githubusercontent.com/113207522/223529092-b343d841-ac0e-41bb-a35e-2ae5c371f092.gif)

Preview with labels:
![output500](https://user-images.githubusercontent.com/113207522/223529363-96214ced-3828-4964-9f81-7084a31e7a32.gif)

**Comment by satkkeerthi** [comment]
Currently the race condition implementation works only for deplaning on this plane model. Currently working on generalizing it with goals.

Also need to work on finding the ideal collision boundary size. For reference, when the collision boundary has a higher x-axis length, the output is as follows:
 
![outputnewrace](https://user-images.githubusercontent.com/113207522/223531264-2a35b5ee-5c52-4844-9a7c-a0b04f19d398.gif)

**Comment by satkkeerthi** [comment]
Continued in #105 and #106
