### ISSUE TITLE
Convert functions from hardcoded 

### ISSUE THREAD

**Issue by rpahle** [vipra-uwf/vipra-1.0#105]

**Comment by satkkeerthi** [comment]
Generalized the functions. Output is as follows:
![outputgwl](https://user-images.githubusercontent.com/113207522/225125719-ad2d9ee0-8ffa-413c-8e7f-7213b1b5fcb7.gif)

Without Labels:
![output](https://user-images.githubusercontent.com/113207522/225126110-be3dc4e8-df11-4869-82df-3dfd1c8adaea.gif)

**Comment by satkkeerthi** [comment]
Continued in #106
