### ISSUE TITLE
Possibly Using 3rd Party Linear Algebra Library

### ISSUE THREAD

**Issue by GoodenoughR** [vipra-uwf/vipra-1.0#85]
I am wondering if we should switch our Dimensions object to a 3rd party linear algebra library implementation?

The library I have looked at specifically is Eigen3:
[https://eigen.tuxfamily.org/](https://eigen.tuxfamily.org/)

**Comment by ashok0srinivasan** [comment]
I don't see any significant linear algebra operations other than vector
operations. So, it would not help, but just add a dependency.

- Ashok Srinivasan
